name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check Out
        uses: actions/checkout@v3.0.2

      - name: Install .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore Rhino.Mocks.sln

      - name: Build the Solution
        run: |
          $tag = ${env:GITHUB_REF} -replace 'refs/tags/v',''
          msbuild Rhino.Mocks.sln /p:Configuration=Release /p:Version=${tag} /p:AssemblyVersion=${tag} /p:FileVersion=${tag}

      - name: ILRepack assemblies
        run: |
          .\ilrepack.ps1 "Rhino.Mocks\bin\release\net35\"
          .\ilrepack.ps1 "Rhino.Mocks\bin\release\netcoreapp3.1\"
          .\ilrepack.ps1 "Rhino.Mocks\bin\release\net6.0\"

      - name: Pack
        run: |
          $tag = ${env:GITHUB_REF} -replace 'refs/tags/v',''
          dotnet pack /p:Configuration=Release --no-restore --no-build /p:Version=${tag} -o .\Rhino.Mocks\bin\release\ .\Rhino.Mocks\Rhino.Mocks.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Rhino.Mocks
          path: Rhino.Mocks\bin\release\*.nupkg

      - name: Push NuGet package to GitHub registry
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: dotnet nuget push Rhino.Mocks\bin\release\*.nupkg --skip-duplicate --no-symbols -s https://nuget.pkg.github.com/rubicon-oss -k "${env:GITHUB_TOKEN}"
